### ISSUE TITLE
num == numcpu issue

### ISSUE THREAD

**Issue by exploshot** [fancoder/cryptonote-universal-pool#44]
node: ../deps/uv/src/unix/linux-core.c:680: read_times: Assertion `num == numcpus' failed.
Aborted

since today i have this Problem. Can somebody explain me that. In special how to fix it.

**Comment by XimmersiveX** [comment]
You ever figure this out?

For anyone else that ends up here with the same problem this is the fix.

I figured out that this error was due to running the pool inside a container. The server itself has 8 CPUs and I had only 4 CPUs assigned to the container. To fix the issue I shut the container down and changed max CPUs to 8. That fixed the issue.

**Comment by exploshot** [comment]
yes i figured it out but i dont know how :D
